name: Memez

on:
  schedule:
    - cron: "40 */1 * * *"
  workflow_dispatch:

jobs:
  sendMemez:

    runs-on: ubuntu-latest
    env:
      IG_USERNAME: ${{secrets.IG_USERNAME}}
      IG_PASSWORD: ${{secrets.IG_PASSWORD}}
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: npm ci --no-audit
    - run: npm run build --if-present
    - run: npm run start
      env:
        CI: true

