name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: true
      IG_USERNAME: ${{secrets.IG_USERNAME}}
      IG_PASSWORD: ${{secrets.IG_PASSWORD}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: npm ci --no-audit
    - run: npm run lint --if-present
    - run: npm test
    - run: npm run build --if-present
